### ISSUE TITLE
mapbox.com site styles conflict with examples

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#327]
First v1 example is ready.

But getting pwned by broad styles in mapbox.com's stylesheet:

![](http://dl.dropbox.com/u/68059/Screenshots/rufsj5d4nuhs.png)

@heyitsgarrett we should make sure that our styles are super strong, and even use `!important` if we must

**Comment by heyitsgarrett** [comment]
![](http://i261.photobucket.com/albums/ii47/drivinsouth/shudder.gif)

Looking into it now

**Comment by heyitsgarrett** [comment]
So just using mapbox.com as an example, these are all the styles being applied:

``` css
.button.big, input[type=submit], input[type=button] {
    box-shadow: rgba(0,0,0,0.05) 0px 0px 0px 5px;
    box-sizing: border-box;
    height: 40px;
    padding: 10px 10px;
    font-size: 15px;
    font-family: 'Opensans Condensed',Arial,sans-serif;
    text-transform: uppercase;
    min-width: 100px;
}
.button, .buttons a, input[type=button], input[type=submit] {
    text-align: center;
    background-color: #3887be;
    cursor: pointer;
    margin: 0px 10px 0px 0px;
}
.badge, .button, .buttons a, input[type=button], input[type=submit] {
    text-decoration: none !important;
    color: #fff;
    display: inline-block;
    vertical-align: middle;
    padding: 0px 10px;
    font-size: 12px;
    letter-spacing: 0px;
    line-height: 20px;
    height: 20px;
    border: 0px;
    overflow: hidden;
    white-space: nowrap;
    border-radius: 4px;
    text-shadow: rgba(0,0,0,0.2) 0px -1px;
    -webkit-appearance: none;
}
```

I'm torn as to what to do about this, as it would really mean having to right a reset override for most CSS styles and applying that to several of our interaction elements. As a utility, I think mapbox.js is best served not taking control of that and the responsibility of handling less aggressive styles should fall to the site owners (obviously, also us in this case, but on the other end)
