### ISSUE TITLE
Examples gallery

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#33]
Let's build out a big, beautiful examples gallery as part of this. This'll serve as a good test suite as well as a good place to show off proper coding patterns with mapbox.js.

Assuming that we'll need a skeleton to start out with ( @tristen lead as soon as you're done with a site revision ) and then we can all claim examples we want to build / port over.

**Comment by tristen** [comment]
Will update this shortly. I started building out the site some yesterday: http://mapbox.com/mapbox.js as soon as the template for the example pages has settled we can start adding examples to it.

**Comment by tristen** [comment]
cc @willwhite as we talked in chat about this being a part of the documentation sprint.

**Comment by tristen** [comment]
Sorry about the delay on this. I think I'm at a good place on the demo gallery site: http://mapbox.com/mapbox.js

Submitting an example should hopefully be pretty straight forward:
- The naming pattern of a demo file is `_posts/examplename/0100-01-01-examplename.html`
- Each file requires a yaml header with the following fields:
  
  ``` yaml
  ---
  layout: example
  categories: example
  title: Simple Map
  description: Create a simple bare bones map using the auto method.
  tags:
    - implementation
  ---
  ```
- When you add a code example you just need to include everything within `<body></body>` the site should do the rest by compiling it into a nice code snippet with doctype see: https://github.com/mapbox/mapbox.js/blob/gh-pages/_layouts/example.html

I've also added a note about adding the newest version of mapbox.js in the README section.

cc @aibram @tmcw We should start adding examples before Friday.
