### ISSUE TITLE
Match width of TileMill & tiles.mapbox.com legends

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#452]

**Comment by tmcw** [comment]
.map-tooltip

v1

``` css
.map-tooltip {
    min-width:180px;
    max-width:280px;
    max-height:400px;

    overflow:auto;
    width:220px\8; /*< IE 9*/
}
```

v0.6.7

``` css
.map-legends,
.map-tooltip {
  min-width:180px;
  max-width:280px;
  max-height:400px;
  width:220px\8; /*< IE 9*/
}
```

tilemill

``` css
.wax-tooltip {
  min-width:100px;
  max-width:280px;
  max-height:400px;
}
```
