### ISSUE TITLE
Geocoder demo has CSS issues

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#467]
[the geocoder demo](http://www.mapbox.com/mapbox.js/example/v1.0.0/geocoding/) gets hit by

``` css
#demo *:not(.zoomer) {
box-sizing: content-box;
-moz-box-sizing: content-box;
}
```

in mapbox's site CSS
