### ISSUE TITLE
GridControl map-clickable class being used?

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox.js#594]
I noticed that a GridControl manages a `.map-clickable` class [on mouseover](https://github.com/mapbox/mapbox.js/blob/master/src/grid_control.js#L78). However, there are no CSS rules that deal with the class. Is that by design?

At first glance it seems a rule like this one might be useful

``` css
.map-clickable { cursor: pointer; }
```
