### ISSUE TITLE
Why is the CSS for changing the cursor of overlay pane not part of mapbox.css?

### ISSUE THREAD

**Issue by ubergesundheit** [mapbox/mapbox.js#729]
I was trying out the [Centering Markers](https://www.mapbox.com/mapbox.js/example/v1.0.0/centering-markers/) example when I noticed that the cursor for the markers don't change when trying the example locally..

Upon digging around in the example page html on mapbox.com I found the following css added:

``` css
.leaflet-overlay-pane path, .leaflet-marker-icon {
    cursor: pointer;
}
```

Why isn't this part of `mapbox.css`?

Cheers
